# This is a basic workflow to help you get started with Actions

name: Lint and create release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3.0.0
        with:
          # TFLint version to install
          tflint_version: latest
          # GitHub token - used when getting the latest version of tflint
          github_token: ${{ github.token }}
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Get latest release version
        id: get-release
        run: |
          # Make a GET request to the GitHub API to fetch the latest release
          response=$(curl -sS --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          # Extract the "tag_name" field from the response using jq
          release_version=$(echo "$response" | jq -r '.tag_name')

          # Set the output "version" to make it accessible to other steps
          echo "::set-output name=version::$release_version"

      - name: Display latest release version
        run: |
          # Access the output "version" from the previous step
          echo "Latest release version: ${{ steps.get-release.outputs.version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${GITHUB_REF#refs/*/}
          release_name: Release ${GITHUB_REF#refs/*/}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
