name: Test Tailscale

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: prashantsolanki3/actions@main
        with:
          authkey: tskey-auth-kCBADm3CNTRL-m8YrdS2SmPjxviLzzwB6Pjr2RLLuhJV3

      - name: Test connection
        run: ping -c 2 datahoarder
      
      - name: TEST SSH
        run: |
          ssh-keyscan compute >> ~/.ssh/known_hosts
          ssh -vvv root@compute "echo 'hello world'"
