name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install Cloudflare Warp Client
        run: |
          # Add cloudflare gpg key
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
                
          # Add this repo to your apt repositories
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
    
          # Install
          sudo apt-get update && sudo apt-get install cloudflare-warp
      
      - name: Configure Cloudflare Warp Client
        run: |
          warp-cli --accept-tos teams-enroll prashant-home
          sleep 15
      - name: Register WARP
        run: warp-cli --accept-tos register
      - name: Check Cloudflare Warp Client Status
        run: warp-cli --accept-tos account
      - name: Connect to Cloudflare Warp Client
        run: warp-cli --accept-tos connect
      - name: Check Cloudflare Warp Files
        run: |
          ls -la /etc/cloudflare-warp
          ls -la /etc/wireguard
      - name: Test connection
        run: ping 172.16.1.1
      # - name: HashiCorp - Setup Terraform
      #   uses: hashicorp/setup-terraform@v2.0.3
        
      # - name: Install ansible
      #   run: python3 -m pip install ansible
      
      # - name: terraform init
      #   run: terraform init

      # - name: terraform-apply
      #   run: terraform apply -var-file=/mnt/env/vm-playground/terraform.tfvars -state=/mnt/env/vm-playground/state/terraform.tfstate --auto-approve
