name: Test Tailscale

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tailscale:  
    uses: prashantsolanki3/actions/.github/workflows/setup-tailscale.yml@main
    with:
      authkey: tskey-auth-kCBADm3CNTRL-m8YrdS2SmPjxviLzzwB6Pjr2RLLuhJV3

  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Test connection
        run: ping -c 2 datahoarder
      
      - name: TEST SSH
        run: |
          ssh-keyscan compute >> ~/.ssh/known_hosts
          ssh -vvv -o StrictHostKeyChecking=no root@compute "echo 'hello world'"
