name: Test Tailscale

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: prashantsolanki3/composite-actions@tailscale
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Test connection
        run: ping -c 2 datahoarder
      
      - name: TEST SSH
        run: |
          ssh-keyscan compute >> ~/.ssh/known_hosts
          ssh root@compute "echo 'hello world'"
